GET https://phonebook-part3-backend.onrender.com/api/persons
####
POST https://phonebook-part3-backend.onrender.com/api/persons
Content-Type: application/json

{
    "name": "POST",
    "number": "24131121"
}

####
DELETE https://phonebook-part3-backend.onrender.com/api/persons/3
