GET http://localhost:3001/api/persons
####
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "POST",
    "number": "24131121"
}

####
DELETE http://localhost:3001/api/persons/3
